version: '2'

services:
  web:
    image: almereyda/transformap-api
    expose:
      - "5000"
    links:
      - geocouch:geocouch
  geocouch:
    image: almereyda/geocouch
    expose:
      - "5984"
