version: '2'

services:
  web:
    image: TransforMap/data.transformap.co
    expose:
      - "5000"
    links:
      - geocouch:geocouch
  geocouch:
    image: 14mmm/geocouch
    expose:
      - "5984"
